import Navbar from "@/components/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import ContextProvider from "@/context/ContextProvider";
import { Toaster } from "@/components/ui/toaster";
import ReduxProvider from "@/providers/ReduxProvider";
import IsLoginProvider from "@/providers/IsLoginProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <Navbar />
          <IsLoginProvider>{children}</IsLoginProvider>
          <Toaster />
        </ReduxProvider>
      </body>
    </html>
  );
}
